### ISSUE TITLE
是否有必要选择一个通行的语言？

### ISSUE THREAD

**Issue by Hansimov** [uupers/devtools#1]
选择一门通行的语言有利于之后写作大规模的项目。

目前群内的开发工具或编程语言包括：
Python，C/C++，Pascal，C#，Java，
Mathematica，MATLAB，Processing，各类作图工具

已有的做法是按照项目来划分，选择什么工具由项目的组员来确定。

各位对此有何想法？

**Comment by HydrogenDeuterium** [comment]
个人认为必要性不大。
毕竟团队不可能说是强迫每个成员都去学同一种语言。
另外为了学习这种语言所花费的时间成本也是个问题。
但是考虑到统一语言带来的兼容性好处，本人对此持保留意见。
等等……我什么语言都不会，是否同意好像对我没有影响？
（准确的说除了自然语言之外只学了个皮毛）

**Comment by Nintha** [comment]
假设群里50%的人都会py，那么基本上大部分项目会以py作为主要语言(现在top language是py了)。
ps:我不会py

**Comment by yxlllc** [comment]
建议每个项目至少有一个python版本，如果自己不会的话可以是专门翻译的成员来做，或者没法翻译的话则做接口，这个可以以后再说。

**Comment by ssysm** [comment]
个人感觉看项目大小或者需求来选择编程语言，我同意@HydrogenDeuterium的说法，如果统一语言的话，每个成员需要参加来学习新的语言是个不小的问题。

我感觉如果说是通用性的话NodeJS、Java、Go和Python是个不错的选择，至于各自的缺点或者优点每个语言都有不同的地方，所以很难决定。

既然说有大规模项目的话我感觉Go和Python可以有，考虑到Java过于庞大，NodeJS现有的大规模生产工具不多，不过对于NodeJS的未来大规模生产工具，可以期待。

至于 作图工具...个人倾向Matlab，processing可以在考虑范围内，毕竟processing不是专业画图的（?）
