### ISSUE TITLE
是否要开团队邮箱以及接受捐赠

### ISSUE THREAD

**Issue by LePtC** [uupers/devtools#2]
目前团队的联系方式填的是我的邮箱，是否要开一个团队邮箱？这样管理员都可以查看

@Leoleepz 提议留个接受捐赠的方式，我觉得留我自己的微信号不太好，有没有什么公共的接受捐赠的方式？

**Comment by LePtC** [comment]
`KaiserKatze` 指出可以开一个邮箱，然后用邮箱开支付宝帐号收捐赠
我跟 `yxlllc` 上联了下，钦定 `KaiserKatze` 来管理这方面的财务了
`KaiserKatze` 在团队成员的介绍更新为：本群吉祥物——招财猫

**Comment by Hansimov** [comment]
> ping 了一分钱过去 

哇，土豪！:kissing_smiling_eyes:

**Comment by Hansimov** [comment]
> 目前团队的联系方式填的是我的邮箱，是否要开一个团队邮箱？

感觉还是暂时先用个人邮箱，毕竟这样处理事情的效率要高一点。

> 我跟 yxlllc 商量了下，钦定 KaiserKatze 来管理这方面的财务了

黑幕？

**Comment by LePtC** [comment]
> 感觉暂时还是先用个人邮箱，毕竟这样处理事情的效率要高一点。

邮箱设了我和 @yxlllc 的自动转发了

> 黑幕？

首先要把权利分散，所以咱们三个管理员就不担财务了， @donizyo 是咱们团队中我认识时间最长的网友（since 2013？），我们互相知晓对方实名信息，~~而且他恰好又是吉祥物~~，所以就钦定他啦

**Comment by Hansimov** [comment]
> 所以就钦定他啦

我说的黑幕是一个梗… :joy:
